### ISSUE TITLE
incorrect reference to ark?

### ISSUE THREAD

**Issue by j-b-m** [appimage-packages/kdenlive#4]
In the Recipe.erb file, the last line contains a zsyncmake command with a reference to ark, not sure if this is correct. Same thing in the kdenlive-stable repository...

zsyncmake -u "https://s3-eu-central-1.amazonaws.com/ds9-apps/ark-appimage/master/$APPIMAGEFILENAME" -o /appimage/<%= name %>_latestversion.zsync /appimage/$APPIMAGEFILENAME

**Comment by ScarlettGatelyMoore** [comment]
I see now, thank you.
